[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
ffi = false
fs_permissions = [{ access = "read", path = "./out" }]
remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "v4-periphery/=lib/v4-periphery/",
  "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/v4-core/lib/solmate/",
]

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 64
fail_on_revert = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
